### ISSUE TITLE
The Balance of Light and Shadow helper module

### ISSUE THREAD

**Issue by shikulja** [madScripting/TurtleWoW-RelarBigWigs#1]
- can check the beginning and end of the event, the number of civilians killed, and calculate the percentage of readiness.
- can check if the quest is reset and add a countdown timer.
- Not sure, but can try to count the number of poisoned targets

**Comment by madScripting** [comment]
Hello shikulka,

I believe you are talking about this quest?
[https://www.wowhead.com/classic/quest=7622/the-balance-of-light-and-shadow](url)

Are you asking for a module to be made with the parameters you mentionned?

Or is there an issue with a current module?

**Comment by shikulja** [comment]
@madScripting 
Yes, this is a request for a new module for this quest.

There is also a problem with capturing friendly targets that are not a group or raids - in this case, it is possible to add an additional concole command to select the most relevant target for treatment. For example: 1. Poisoned by a strong poison 2. Poisoned by a weak poison with the lowest health 3.
Not poisoned with the lowest health.) This is the most necessary thing, but most likely it will not be implemented.

**Comment by shikulja** [comment]
The version is based on an older version of BW (Hosq perhaps). Xorann has developed the right ideas in the new version of BW, the main module code does not depend on server changes.
It’s easier to develop code without worrying about server-side timer differences.
My interest in this fork has disappeared. Good luck, I hope you continue to develop the project.

**Comment by madScripting** [comment]
I haven't found such module on Xorann's, Hosq's, or Vnm's Bigwigs.
I personnally have never heard about it, but that is not suprising as I've never played a priest past level 38!

I don't mind coding it but someone would have to provide the data as I have no idea what that quest is or what the challenges are...

The issues about server/bigwigs compatibility isn't only within the core. The wording of events, category of constants, source of spells, triggers are all different. Even if the core is compatible, all the other modules are a hot pile of crap if they aren't looked into.

**Comment by shikulja** [comment]
![Uploading Снимок экрана 2023-11-02 230143.png…]()
![Снимок экрана 2023-11-02 230256](https://github.com/madScripting/TurtleWoW-RelarBigWigs/assets/3386359/954be612-bb64-42b4-a5de-9fb1b7f7e720)

![Снимок экрана 2023-11-02 230404](https://github.com/madScripting/TurtleWoW-RelarBigWigs/assets/3386359/d1ccc1d2-4976-40c2-a638-8b79df5a665b)

Most TW changes should not affect the main code, and even if there are specific changes, it would still be better.
