### ISSUE TITLE
New Chromaggus timers

### ISSUE THREAD

**Issue by EyeOfTheBeast** [madScripting/TurtleWoW-RelarBigWigs#3]
Information about the new Chromaggus timers can be found in this YouTube video by Vrograg Fishslayer: https://youtu.be/Z-nJEacJu4E?si=V9_SlVyoJTVivcBu&t=288

The current elemental vulnerability timers last too long (45 seconds), they should be updated to 20 second timers now.

![image](https://github.com/madScripting/TurtleWoW-RelarBigWigs/assets/142637959/73641691-fb84-4952-82b8-3c1624e3d279)
![image](https://github.com/madScripting/TurtleWoW-RelarBigWigs/assets/142637959/8554f190-ff8e-46dd-b130-93612eb437b2)

**Comment by madScripting** [comment]
Fixed in rev 30037, thanks for your support.
